#!/bin/sh

# First argument (if any) should be the audience (teacher student volunteer self-guided)
# Second argument (if any) should be the distribution target (bootstrap codeorg)
# Args default to teacher and codeorg

# build the notes
if [ "$2" ]
then
  racket -l errortrace -t build.rkt -- --audience $1 --buildfor $2
elif [ "$1" ]
then
  racket -l errortrace -t build.rkt -- --audience $1 --buildfor bootstrap
else
  racket -l errortrace -t build.rkt -- --audience teacher --buildfor bootstrap
fi  

# then build the solutions
racket -l errortrace -t build-sols.rkt 
 
  