#!/bin/sh

# Arguments:
# --language XXX : some courses may be translated into other languages. As for now, only Algebra is available in english (en-us) and spanish (es-mx)
# --course YYY   : e.g - "algebra" or "data-science"

# build the notes

racket -l errortrace -t build-workbook.rkt -- "$@"

# then build the solutions
#racket -l errortrace -t build-sols.rkt 