#!/bin/sh


# echo "BUILDING TEACHER WORKBOOK\n"
./build-workbook --solutions --language spanish "$@"

# build the workbook (for students)
echo "\nBUILDING STUDENT WORKBOOK\n"
./build-workbook --language spanish "$@"

echo "\nBUILDING NOTES AND RESOURCES\n"
./build-notes --language spanish "$@"
