#!/bin/sh

# First argument (if any) should be the audience (teacher student volunteer self-guided)
# Second argument (if any) should be the distribution target (bootstrap codeorg)
# Args default to teacher and codeorg

# and the workbook solutions manual
echo "BUILDING TEACHER WORKBOOK"
./build-workbook --solutions --language spanish
./build-workbook --solutions --language english

# build the workbook (for students)
echo "BUILDING STUDENT WORKBOOK"
./build-workbook --language english
./build-workbook --language spanish

echo "BUILDING NOTES AND RESOURCES"
./build-notes "$@"

 
  