#!/bin/sh

# First argument (if any) should be the audience (teacher student volunteer self-guided)
# Second argument (if any) should be the distribution target (bootstrap codeorg)
# Args default to teacher and codeorg

# build the workbook (for students)
racket -l errortrace -t build-workbook.rkt

# and the workbook solutions manual
racket -l errortrace -t build-workbook.rkt --solutions

./build-notes "$@"

 
  