#!/bin/sh

# Arguments:
# --language XXX : some courses may be translated into other languages. As for now, only Algebra is available in english and spanish
# --course YYY   : e.g - "algebra" or "data-science"

# build the notes

racket -l errortrace -t build.rkt -- "$@"

# then build the solutions
#racket -l errortrace -t build-sols.rkt