#!/bin/sh


# echo "BUILDING TEACHER WORKBOOK\n"
./build-workbook --solutions --language english

# build the workbook (for students)
echo "\nBUILDING STUDENT WORKBOOK\n"
./build-workbook --language english

echo "\nBUILDING NOTES AND RESOURCES\n"
./build-notes --language english "$@"

 