#!/bin/sh



# and the workbook solutions manual
echo "BUILDING TEACHER WORKBOOK\n"
./build-workbook --solutions "$@"

# build the workbook (for students)
echo "\nBUILDING STUDENT WORKBOOK\n"
./build-workbook "$@"

echo "\nBUILDING NOTES AND RESOURCES\n"
./build-notes "$@"
./build-sols.rkt "$@"
