#!/bin/sh

# First argument (if any) should be the audience (teacher student volunteer self-guided)
# Second argument (if any) should be the distribution target (bootstrap codeorg)
# Args default to teacher and codeorg

# and the workbook solutions manual
echo "BUILDING TEACHER WORKBOOK"
racket -l errortrace -t build-workbook.rkt -- --solutions

# build the workbook (for students)
echo "BUILDING STUDENT WORKBOOK"
racket -l errortrace -t build-workbook.rkt

echo "BUILDING NOTES AND RESOURCES"
./build-notes "$@"

 
  