;; This file contains the index for pages that we will extract from
;; the manually-maintained workbook.  We will use this to find pages
;; within the PDF file, based on their tag names

(
 ("Expressions-Values-Errors" 1)
 ("Identifiers-Expressions" 2)
 ("Contracts-Functions" 3)
 ("Animals" 4)
 ("Presidents-Nutrition" 5)
 ("Mean-Median-Mode" 6)
 ("Measuring-Center" 7)
 ("Questions-With-Charts" 8)
 ("Freq-Bar-Chart" 9)
 ("Chart-Practice" 10)
 ("More-Chart-Practice" 11)
 ("Histograms" 12)
 ("Histograms-Practice" 13)
 ("Scatter-Plot" 14)
 ("Grading-Predictors" 15)
 ("More-Predictors" 16)
 ("Select-Practice" 17)
 ("Select-Continued" 18)
 ("Order-Practice" 19)
 ("Rows-Questions" 20)
 ("Booleans-Comparison" 21)
 ("Sieve-Practice" 22)
 ("Extending-Tables" 23)
 ("Countries-Example" 24)
 ("Nutrition-Plan" 25)
 ("Presidents-Plan" 26)
 ("Rainfall-Plan" 27)
 ("Countries-Plan" 28)
 ("General-Table-Plan" 29)
 ("General-Table-Plan" 30)
)
