  (("funciones de acceso" "funciones para extraer valores de una estructura de datos")
    ("aplicando" "use una función dada en algunas entradas")
    ("argumentos" "las entradas de una función, las expresiones de los argumentos siguen el nombre de una función")
    ("booleano" "un tipo de datos con dos valores: true y false")
    ("llamada" "Utilizando una función dándole entradas")
    ("círculo de evaluación" "un diagrama de la estructura de una expresión (aritmética o código)")
    ("cláusula" "una pregunta y su respuesta correspondiente en una expresión condicional")
    ("condicional" "una expresión de código hecha de preguntas y respuestas")
    ("función constructor" "La función que crea una estructura de datos particular")
    ("contrato" "una declaración del nombre, dominio y rango de una función")
    ("estructura de datos" "Un grupo de valores que se pueden devolver como un único tipo de datos")
    ("tipo de datos" "Una manera de clasificar valores, como: Número, Cadena, Imagen o Booleano")
    ("tipos de datos" "Una forma de clasificar valores, como: Número, Cadena, Imagen o Booleano")
    ("define" "asociar un nombre descriptivo con un valor")
    ("área de definiciones" "el cuadro de texto en el Editor (DrRacket o WeScheme), donde se escriben definiciones de valores y funciones")
    ("receta de diseño" "una secuencia de pasos que ayuda a las personas a documentar, probar y escribir funciones")
    ("dominio" "el tipo de datos que espera una función")
    ("dot-accessors" "Una manera de extraer valores de una estructura de datos")
    ("editor" "software en el que se puede escribir y evaluar código")
    ("mensaje de error" "información del equipo sobre errores en el código")
    ("mensajes de error" "información del equipo sobre errores en el código")
    ("evaluar" "realizar el cálculo en una expresión, producir una respuesta")
    ("equivale a" "el resultado de calcular una expresión")
    ("programacion basada en eventos" "un estilo de programación en el que se escriben todas las funciones para responder a los clics del ratón, pulsaciones de teclas, etc.")
    ("eventos" "algo que sucede fuera de un programa en ejecución, al que el programa puede responder")
    ("ejemplos" "muestra el uso de una función en entradas específicas y el cálculo que debe realizar la función en esas entradas")
    ("expresiones" "un cálculo escrito en las reglas de algún lenguaje (como aritmética, código o un Círculo de Evaluación)")
     ("expresión" "un cálculo escrito en las reglas de algún lenguaje (como aritmética, código o un Círculo de Evaluación)")
    ("definición de función" "que designa una función, enumera sus variables e indica la expresión a calcular cuando se utiliza la función")
    ("función" "un objeto matemático que toma en algunas entradas y produce una salida")
    ("funciones" "un objeto matemático que toma en algunas entradas y produce una salida")
    ("hipotenusa" "el lado opuesto al ángulo de 90 grados en un triángulo rectángulo")
    ("imagen" "un tipo de datos para imágenes")
    ("área de interacciones" "el cuadro de texto en el Editor (DrRacket o WeScheme), donde entramos expresiones para evaluar")
    ("instancias" "Valores específicos de datos")
    ("expresión legal" "expresión que sigue las Reglas de Código para un lenguaje de programación")
    ("expresión matemática" "un cálculo en aritmética")
    ("funciones por trozos" "una función que calcula diferentes expresiones basadas en su entrada")
    ("nombre" "cómo nos referimos a una función o valor definido en un idioma (ejemplos: +, *, estrella, círculo)")
    ("producen" "para calcular un valor de una expresión")
    ("lenguaje de programación" "un conjunto de reglas para escribir código que una computadora puede evaluar")
    ("declaración de propósito" "una breve descripción de lo que hace una función")
    ("rango" "el tipo de datos que produce una función")
    ("cadena de texto" "cualquier secuencia de caracteres entre comillas (ejemplos: \"hello\", \" 42\", \"esto es una cadena! \")")
    ("sintaxis" "El conjunto de reglas que define un lenguaje, ya sea que se hable, se escriba o se programe.")
    ("tipo" "se refiere a un tipo general de datos, como Number, String, Image o Boolean")
    ("tipos" "se refiere a un tipo general de datos, como Number, String, Image o Boolean")
    ("unidad de prueba" "un ejemplo que muestra el uso de una función con un valor o valores específicos y la respuesta que debe producir")
    ("valores" "una pieza específica de datos, como 5 o \" hello \"")
    ("valor" "una pieza específica de datos, como 5 o \" hello \"")
    ("variable" "algo que cambia")
    ("nombre de variable" "nombre de la información que puede ser diferente cada vez que se utiliza una función")
    ("accessor functions" "functions to extract values from a data structure")
    ("apply" "use a given function on some inputs")
    ("arguments" "the inputs to a function; expressions for arguments follow the name of a function")
    ("boolean" "a type of data with two values: true and false")
    ("calling" "Using a function by giving it inputs")
    ("circle of evaluation" "a diagram of the structure of an expression (arithmetic or code)")
    ("clause" "a question and its corresponding answer in a conditional expression")
    ("conditional" "a code expression made of questions and answers")
    ("constructor function" "The function that creates a particular data structure")
    ("contract" "a statement of the name, domain, and range of a function")
    ("data structure" "A group of values that can be returned as a single datatype")
    ("data type" "A way of classifying values, such as: Number, String, Image, or Boolean")
    ("data types" "A way of classifying values, such as: Number, String, Image, or Boolean")
    ("definitions area" "the text box in the Editor (DrRacket or WeScheme), where definitions for values and functions are written")
    ("design recipe" "a sequence of steps that helps people document, test, and write functions")
    ("domain" "the type of data that a function expects")
    ("dot-accessors" "A way to extract values from a data structure")
    ("error message" "information from the computer about errors in code")
    ("evaluate" "perform the computation in an expression, producing an answer")
    ("evaluates to" "the result of computing an expression")
    ("event-based programming" "a style of programming in which every functions are written to respond to mouse-clicks, keypresses, etc.")
    ("events" "something that happens outside of a running program, which the program can respond to")
    ("example" "shows the use of a function on specific inputs and the computation the function should perform on those inputs")
    ("expression" "a computation written in the rules of some language (such as arithmetic, code, or a Circle of Evaluation)")
    ("function definition" "code that names a function, lists its variables, and states the expression to compute when the function is used")
    ("function" "a mathematical object that takes in some inputs and produces an output")
    ("hypotenuse" "the side opposite the 90-degree angle in a right triangle")
    ("image" "a type of data for pictures")
    ("interactions area" "the text box in the Editor (DrRacket or WeScheme), where we enter expressions to evaluate")
    ("instances" "Specific values of data")
    ("legal expression" "code that follows the Code Rules for a language")
    ("mathematical expression" "a computation in arithmetic")
    ("piecewise function" "a function that computes different expressions based on its input")
    ("name" "how we refer to a function or value defined in a language (examples: +, *, star, circle)")
    ("produce" "to compute a value from an expression")
    ("programming language" "a set of rules for writing code that a computer can evaluate") 
    ("purpose statement" "a brief description of what a function does")
    ("range" "the type of data that a function produces")
    ("string" "any sequence of characters between quotation marks (examples: \"hello\", \"42\", \"this is a string!\")")
    ("syntax" "The set of rules that defines a language, whether it be spoken, written, or programmed.")
    ("type" "refers to a general kind of data, like Number, String, Image, or Boolean")
    ("unit test" "an example showing the use of a function with a specific value or values, and the answer it should produce")
    ("value" "a specific piece of data, like 5 or \"hello\"")
    ("variable" "something that changes")
    ("variable name" "name of the information that can be different each time a function is used")
    )