
#|
Glossary for terminology used in the notes.  The first entry of each entry can be either
a single string or a list of keys that map to the same definition.

If a list of keys is provided, the generated glossary will use the first in the list
when it prints out the glossary for a particular unit
|#

  (("funciones de acceso" "funciones para extraer valores de una estructura de datos")
    ("aplicando" "use una función dada en algunas entradas")
    ("argumentos" "las entradas de una función, las expresiones de los argumentos siguen el nombre de una función")
    ("ascending" "an order in which lower values appear first, and higher values appear after")
    ("average" "A number representing the center, or 'typical' value in a set of data")
    (("axis" "axes") "A number line on a scatter plot, used to place points that represent pairs of values in data sets")
    (("bar chart" "bar charts") "a visualization in which a data set is represented by vertical bars, with length proportional to values")
    (("bin" "bins") "A range that values from a data set can belong to; there is one bar in a histogram per bin")
    ("booleano" "un tipo de datos con dos valores: true y false")
    (("box plot" "box plots") "The box plot (a.k.a. box and whisker diagram) is a way of displaying the distribution of data based on the five-number summary: minimum, first quartile, median, third quartile, and maximum")
    (("llamada" "llamadas") "Utilizando una función dándole entradas")
    (("category" "categories") "the set of possible values that a value in a categorical data set can have")
    ("categorical data" "kind of data with a value that has a fixed number of possible values")
    ("círculo de evaluación" "un diagrama de la estructura de una expresión (aritmética o código)")
    ("cláusula" "una pregunta y su respuesta correspondiente en una expresión condicional")
    (("chart" "charts") "visual reprsentations of how values in a data set are distributed")
    (("column" "columns") "set of values in a table of a particular type.  Every row has exactly 1 element in every column")
    ("condicional" "una expresión de código hecha de preguntas y respuestas")
    ("función constructor" "La función que crea una estructura de datos particular")
    ("contrato" "una declaración del nombre, dominio y rango de una función")
    (("correlation" "correlations") "A relationship between two data sets")
    ("data block" "Code that lists the name, constructor(s), and field(s) of a data structure")
    (("data row" "data rows") "an individual, structured piece of data in a dataset")
    ("data science" "The study of using data to answer questions about the world")
    (("dataset" "datasets") "a collection of related information that is composed of separate elements, but can be manipulated as a unit by a computer")
    (("estructura de datos" "estructuras de datos") "Un grupo de valores que se pueden devolver como un único tipo de datos")
    (("tipo de datos" "tipos de datos") "Una manera de clasificar valores, como: Número, Cadena, Imagen o Booleano")
    ("define" "asociar un nombre descriptivo con un valor")
    ("área de definiciones" "el cuadro de texto en el Editor (DrRacket o WeScheme), donde se escriben definiciones de valores y funciones")
    ("descending" "an order in which higher values appear first, and lower values appear after")
    ("receta de diseño" "una secuencia de pasos que ayuda a las personas a documentar, probar y escribir funciones")
    ("dominio" "el tipo de datos que espera una función")
    ("dot-accessors" "Una manera de extraer valores de una estructura de datos")
    ("editor" "software en el que se puede escribir y evaluar código")
    (("entry" "entries") "a single value in a table, belonging to a particular row and column")
    (("mensaje de error" "mensajes de error") "información del equipo sobre errores en el código")
    ("evaluar" "realizar el cálculo en una expresión, producir una respuesta")
    (("equivale a" "equivale") "el resultado de calcular una expresión")
    ("programacion basada en eventos" "un estilo de programación en el que se escriben todas las funciones para responder a los clics del ratón, pulsaciones de teclas, etc.")
    ("event-based programming" "a style of programming in which every functions are written to respond to mouse-clicks, keypresses, etc.")
    ("eventos" "algo que sucede fuera de un programa en ejecución, al que el programa puede responder")
    ("ejemplos" "muestra el uso de una función en entradas específicas y el cálculo que debe realizar la función en esas entradas")
    ("examples block" "Pyret code that lists examples starting with 'examples:' and ends with 'end'")
    (("expresión" "expresiones") "un cálculo escrito en las reglas de algún lenguaje (como aritmética, código o un Círculo de Evaluación)")
    ("extract" "to construct a list using data from a particular column in a table")
    ("field" "A part of a data structure that has a name and holds a single value of a specified datatype")
    ("definición de función" "que designa una función, enumera sus variables e indica la expresión a calcular cuando se utiliza la función")
    ("function block" "Pyret code that names a function, lists its variables, and states the expression to compute when the function is used")
    (("función" "funciones") "un objeto matemático que toma en algunas entradas y produce una salida")
    (("frequency" "frequencies") "how often a particular value appears in a data set")
    (("frequency bar chart" "frequency bar charts") "A bar chart in which each the length of each bar corresponds to the frequency of a particular value")
    ("handler" "Connects an event (like a tick or keypress) and a function within a reactor")
    (("header row" "header rows") "the titles of each column of a table, usually shown at the top")
    ("helper function" "A small function that handles a specific part of another computation, and gets called from other functions")
    ("header" "The part of a table that identifies the names of each column")
    (("histogram" "histograms") "A special frequency bar chart in which each bar counts the frequency of values appearing that belong to a certain bin")
    ("horizontal axis" "Axis on a scatter plot that runs from left to right")
    ("hipotenusa" "el lado opuesto al ángulo de 90 grados en un triángulo rectángulo")
    ("imagen" "un tipo de datos para imágenes")
    ("área de interacciones" "el cuadro de texto en el Editor (DrRacket o WeScheme), donde entramos expresiones para evaluar")
    ("interquartile range" "The interquartile range (IQR) is a measure of variability, based on dividing a data set into four quartiles. The values that divide each part are called the first (Q1), second (Q2), and third quartiles (Q3)")
    ("instancias" "Valores específicos de datos")
    ("expresión legal" "expresión que sigue las Reglas de Código para un lenguaje de programación")
    (("library" "libraries") "A collection of functions that can be made available to our program by using include")
    (("line of best fit" "lines of best fit") "a straight line that best represents the data on a scatter plot")
    ("linear regression" "a linear approach for modeling the relationship between a dependent variable, and one or more explanatory variables")
    (("list" "lists") "a data structure containing a sequence of values")
    ("expresión matemática" "un cálculo en aritmética")
    ("mean" "the arithmetic mean; a number with the smallest total difference between all elements in a quantitative data set")
    ("method" "a function that is only associated with an instance of a datatype, which consumes inputs and produces an output based on that instance")
    ("median" "the middle element of a quantitative data set")
    ("mode" "the most commonly appearing value in a quantitative data set")
    ("nombre" "cómo nos referimos a una función o valor definido en un idioma (ejemplos: +, *, estrella, círculo)")
    ("negative correlation" "relationship in which one variable increases as the other decreases, and vice versa")
    (("operator" "operators") "a symbol that manipulates two Numbers and produces a result")
    (("order" "orders" "ordering") "An arrangement of data according to some pattern")
    (("outlier" "outliers") "an observation point that is distant from other observations, perhaps due to experimental error or measurement variability.")
    ("funciones por trozos" "una función que calcula diferentes expresiones basadas en su entrada")
    (("pie chart" "pie charts") "A chart where the size of each pie slice corresponds to a value in the data set")
    ("positive correlation" "relationship in which one variable increases as the other increases, and vice versa")
    ("predictor" "a function which, given a value from one data set, tries to predict a related value in a different data set")
    ("producen" "para calcular un valor de una expresión")
    ("lenguaje de programación" "un conjunto de reglas para escribir código que una computadora puede evaluar")
    ("declaración de propósito" "una breve descripción de lo que hace una función")
    ("quartile" "Each of four equal-sized groups into which a population can be divided, according to the distribution of values of a particular variable")
    ("quantitative data" "data with values that measure some amount or quantity;  may not have a fixed number of possible values")
    (("r-squared") "A number between 0 and 1 that measures the strength of association between two variables")
    ("rango" "el tipo de datos que produce una función")
    ("reactor" "A value that contains a current state, and functions for updating, drawing, and interacting with that state")
    (("refactor" "refactoring") "The process of changing the style or structure of a program's code, without changing the program's behavior")
    (("row" "rows") "item(s) in a table, which consist of some group of values; each table is a collection of rows")
    ("sample instances" "A collection of single instances, or also used to describe illustrative instances that we use to provide examples of a data structure")
    (("scatter plot" "scatter plots") "A chart where points are placed on axes according to pairs of values")
    ("state" "The value of a changing system at any point in time (ie - a stoplight can be in the 'red', 'yellow' or 'green' state). In Pyret, the state of a Reactor is it's current value.")
    (("cadena de texto" "cadenas de texto") "cualquier secuencia de caracteres entre comillas (ejemplos: \"hello\", \" 42\", \"esto es una cadena! \")")
    ("sintaxis" "El conjunto de reglas que define un lenguaje, ya sea que se hable, se escriba o se programe.")
    (("table" "tables") "A data structure that stores data as rows, with entries in particular columns")
    ("table plan" "A sequence of steps that helps people write code for several table queries, in order to solve a problem")
    (("table query" "table queries") "An expression that consumes tables and creates a new table object")
    ("tipo" "se refiere a un tipo general de datos, como Number, String, Image o Boolean")
    ("tipos" "se refiere a un tipo general de datos, como Number, String, Image o Boolean")
    ("unidad de prueba" "un ejemplo que muestra el uso de una función con un valor o valores específicos y la respuesta que debe producir")
    ("valores" "una pieza específica de datos, como 5 o \" hello \"")
    ("valor" "una pieza específica de datos, como 5 o \" hello \"")
    ("variable" "algo que cambia")
    ("nombre de variable" "nombre de la información que puede ser diferente cada vez que se utiliza una función")
    ("vertical axis" "Axis on a scatter plot that runs up and down")
    )