#lang racket/base

(provide glossary-terms-dictionary)

(define glossary-terms-dictionary
  '(("apply" "perform the computation for a function on given inputs")
    ("arguments" "the inputs to a function; expressions for arguments follow the name of a function")
    ("boolean" "a type of data with the two values true and false")
    ("circle of evaluation" "a diagram of the structure of an expression (arithmetic or code)")
    ("clause" "a question and its corresponding answer in a conditional expression")
    ("conditional" "a code expression made of questions and answers")
    ("contract" "a statement of the name, domain, and range of a function")
    ("define" "associate a descriptive name with a value")
    ("definitions window" "the upper window in DrRacket or WeScheme where code definitions go")
    ("design recipe" "a sequence of steps that help people document, test, and write functions")
    ("domain" "the type of data that a function expects")
    ("editor" "software in which you can write and evaluate code")
    ("error message" "information from the computer about errors in code")
    ("evaluate" "perform the computation in an expression, producing an answer")
    ("evaluates to" "the value of the computation in an expression")
    ("example" "shows the use of a function on specific inputs and the computation the function should perform on those inputs")
    ("expression" "a computation written in the rules of some language (such as arithmetic, code, or a Circle of Evaluation)")
    ("function" "a mathematical object that produces an output from inputs")
    ("function definition" "code that names a function, lists its variables, and states the expression to compute when the function is used")
    ("image" "a type of data for pictures")
    ("interactions window" "the lower window in DrRacket or WeScheme where we enter expressions to evaluate")
    ("legal expression" "code that follows the Code Rules for a language")
    ("mathematical expression" "a computation in arithmetic")
    ("name" "how we refer to a function (examples: +, *, star, circle)")
    ("piecewise function" "a function that computes different expressions based on its input")
    ("produce" "to compute a value from an expression")
    ("programming language" "a set of rules for writing code that a computer can evaluate") 
    ("purpose statement" "a brief description of what a function does")
    ("range" "the type of data that a function produces")
    ("string" "any sequence of characters between quotation marks")
    ("type" "refers to a general kind of data, like Number, String, Image, or Boolean")
    ("unit test" "an example showing the use of a function and the answer it should produce")
    ("value" "a specific piece of data, like 5 or \"hello\"")
    ("variable" "something that changes")
    ("variable name" "name of the information that can be different teach time a function is used")
   ))