#lang curr/lib

@(include-lesson (lib "curr/lessons/Contracts/worksheets/Contracts.scrbl"))
@(include-lesson (lib "curr/lessons/Ninja-Cat-Demo/worksheets/How-Does-Ninja-Cat-Work.scrbl"))
@(include-lesson (lib "curr/lessons/Ninja-Cat-Demo-Dissection/worksheets/Ninja-Cat-Coordinates.scrbl"))
@(include-lesson (lib "curr/lessons/Ninja-Cat-Demo-Brainstorming/worksheets/Elements-of-a-Videogame.scrbl"))
@(include-lesson (lib "curr/lessons/Circles-of-Evaluation/worksheets/Circles-of-Evaluation-Practice.scrbl"))
@(include-lesson (lib "curr/lessons/Circles-of-Evaluation-Review/worksheets/Circles-of-Evaluation-Practice-2.scrbl"))
@(include-lesson (lib "curr/lessons/Fast-Functions/worksheets/Fast-Functions.scrbl"))
@(include-lesson (lib "curr/lessons/Introducing-the-Design-Recipe/worksheets/Design-Recipe-Rocket-Height.scrbl"))
@(include-lesson (lib "curr/lessons/Practicing-the-Design-Recipe/worksheets/Design-Recipe-Red-Square.scrbl"))
@(include-lesson (lib "curr/lessons/Even-More-Practice-for-Design-Recipe/worksheets/Design-Recipe-Yard-Area.scrbl"))
@(include-lesson (lib "curr/lessons/Danger-Movement/worksheets/Design-Recipe-Update-Danger.scrbl"))
@(include-lesson (lib "curr/lessons/Target-Movement/worksheets/Design-Recipe-Update-Target.scrbl"))
@(include-lesson (lib "curr/lessons/onscreen1/worksheets/Protecting-Sam.scrbl"))
@(include-lesson (lib "curr/lessons/onscreen1/worksheets/Design-Recipe-Protect-Left.scrbl"))
@(include-lesson (lib "curr/lessons/onscreen1/worksheets/Design-Recipe-Protect-Right.scrbl"))
@(include-lesson (lib "curr/lessons/Boolean-Function/worksheets/AND-and-OR.scrbl"))
@(include-lesson (lib "curr/lessons/onscreen2/worksheets/Design-Recipe-Onscreen.scrbl"))
@(include-lesson (lib "curr/lessons/Cond-Example-With-Pizza-Toppings/worksheets/Design-Recipe-Cost.scrbl"))
@(include-lesson (lib "curr/lessons/Player-Movement/worksheets/Design-Recipe-Update-Player.scrbl"))
@(include-lesson (lib "curr/lessons/1D-Distance/worksheets/Design-Recipe-Line-Length.scrbl"))
@(include-lesson (lib "curr/lessons/Distance-Formula/worksheets/Distance-Formula-With-Numbers.scrbl"))
@(include-lesson (lib "curr/lessons/Distance-Formula/worksheets/Distance.scrbl"))
@(include-lesson (lib "curr/lessons/Collision-Detection/worksheets/collide.scrbl"))
@(include-lesson (lib "curr/lessons/Function-Example-Red-Shape/worksheets/red-shape.scrbl"))
